### PR TITLE
Add option to use locate to list repos

### PR DESCRIPTION
**Pull request by cljoly**
- refactor: isolate picker creation
- feat: add cached_list
- fix: change prompt for the various commands

### CODE REVIEW

**Comment by cljoly** [comment]
There is a bug in the construction of the repository list (we get the .git, not the repo itself).

**Comment by cljoly** [comment]
You should be able to run `cached_list` the first time. Have you populated the cache with `sudo updatedb` first though?

**Comment by cljoly** [comment]
Also, does `locate -r '/.git$'` return anything for you?

**Comment by molleweide** [comment]
> You should be able to run `cached_list` the first time. Have you populated the cache with `sudo updatedb` first though?

returns command not found on macos

**Comment by molleweide** [comment]
> Also, does `locate -r '/.git$'` return anything for you?

returns on macos

```shell
locate -r '/.git$'
locate: illegal option -- r
usage: locate [-0Scims] [-l limit] [-d database] pattern ...

default database: `/var/db/locate.database' or $LOCATE_PATH
```

**Comment by molleweide** [comment]
BUT my terminal is a bit messed up at the moment tho so I cant be hundred percent sure everything returns correctly.

**Comment by molleweide** [comment]
What linux are you using?

**Comment by molleweide** [comment]
i have been searching a bit and I don't know if I have come up with anything useful yet, but it seems that you need a different command for locate on macos.

**Comment by molleweide** [comment]
You're preview looks good!

**Comment by cljoly** [comment]
> What linux are you using?

Mostly Arch linux.

**Comment by cljoly** [comment]
> You're preview looks good!

Thanks!

**Comment by molleweide** [comment]
> > What linux are you using?
> 
> Mostly Arch linux.

cool, my goal is to migrate to that in the future.

**Comment by molleweide** [comment]
i find this thread on  how to use `locate` on macos:
https://www.codeproject.com/Tips/5282703/Using-locate-databases-on-MacOS-Unix
BUT
there is also this saying that locate is not supported on mac and you should instead use a command called `mdfind`.
https://stackoverflow.com/questions/59881380/command-locate-in-mac-terminal.
https://metaredux.com/posts/2019/12/22/mdfind.html

I'm just posting here for reference. I have to look into this and see if you can create some kind of OS conditional.

**Comment by cljoly** [comment]
> i have been searching a bit and I don't know if I have come up with anything useful yet, but it seems that you need a different command for locate on macos.

Yeah, I’ve found `mdfind` that seems to use spotlight’s cache (which is great), but it looks like it does not support hidden files (and I’m looking for `.git` to find the repos).

**Comment by cljoly** [comment]
Our posts crossed it seems :)

**Comment by molleweide** [comment]
Hmmm that's a bummer

**Comment by cljoly** [comment]
Looks like you can get `locate` installed on macos with brew: https://egeek.me/2020/04/18/enabling-locate-on-osx/

**Comment by molleweide** [comment]
> Looks like you can get `locate` installed on macos with brew: https://egeek.me/2020/04/18/enabling-locate-on-osx/

Wow I'll try that later today. It is wierd also because I get some indication it seems that some kind of locate exists on my machine but it doesn't have the -r flag. Hopefully it works without any mods with this brew package.

**Comment by cljoly** [comment]
Yeah, I suspect the version of locate that you have installed currently does not support the `-r` but the `findutils` version should.

**Comment by molleweide** [comment]
allright, so now I have installed it and aliased it like so:
```
  alias locate="glocate -d $HOME/locatedb"
```

Should trepo pick up on this or do I have to change anything in the source you think?

**Comment by molleweide** [comment]
oh nvm now I think I understand how to add it.

**Comment by cljoly** [comment]
You would need the “more arguments” thing (not implemented yet) for the `-d $HOME/locatedb` bit, but glocate should work if passed to `bin`.

You should be able to test just by changing the command [here](https://github.com/cljoly/telescope-repo.nvim/pull/9/files#diff-d075801b3fac5560177ed9328337c45d39d04f697d5edf133099e432697df49bR162)

**Comment by molleweide** [comment]
> You would need the “more arguments” thing (not implemented yet) for the `-d $HOME/locatedb` bit, but glocate should work if passed to `bin`.
> 
> You should be able to test just by changing the command [here](https://github.com/cljoly/telescope-repo.nvim/pull/9/files#diff-d075801b3fac5560177ed9328337c45d39d04f697d5edf133099e432697df49bR162)

cool yeah I've tried that now and it does not work at first try.
ima take a pause now and come back later. but searching
the db in the terminal works.

**Comment by molleweide** [comment]
could flag order be of importance?

**Comment by molleweide** [comment]
naaah

**Comment by cljoly** [comment]
If you want, you can paste the files you have changed in a [gist](https://gist.github.com/), I can take a look.

**Comment by molleweide** [comment]
https://gist.github.com/molleweide/2599344a4e3e7cceb11b71ff6064343f

cool l have never created a gist before. is it free to make or whatever.

**Comment by molleweide** [comment]
i ll comment over there

**Comment by cljoly** [comment]
I’ve answered there, for when you want to get back to it.

**Comment by molleweide** [comment]
hey what to you use for `--prunepath`? 

I think this could be the culprit!

In the article he uses `--prunepaths=/Volumes` but that doesn't seem right because when
I look into that dir it doesn't contain my $HOME. I cant explain exactly because it seems to b some kind of
clean copy of my user dir
I am thinking that I should now that I should set the prune path to `$HOME`.

**Comment by cljoly** [comment]
My understanding is that `--prunepath` is a list of directories not to explore further, but we can try…

**Comment by molleweide** [comment]
aaah so it ignores that!!

**Comment by cljoly** [comment]
Yep.

**Comment by molleweide** [comment]
What have you set your own updatedb command to?

**Comment by cljoly** [comment]
I just run `updatedb`, but it reads the global configuration like so:
https://gist.github.com/65a65af3c8f797fee31e6d4151247aea

**Comment by cljoly** [comment]
> However, when I opened up the locatedb file and searched for eg. telescope-repo, it did not find any matches in that file.

But does
```
glocate -d $HOME/locatedb -r '/.git$'
```
return anything in your terminal?

**Comment by molleweide** [comment]
good question again. I ran that command before and forgot to post the result here:
``` shell
/System/Volumes/Data/usr/local/Cellar/git/2.33.0_1/share/zsh/site-functions/_git
/System/Volumes/Data/usr/local/Cellar/zsh/5.8_1/share/zsh/functions/_git
/System/Volumes/Data/usr/local/Homebrew/.git
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/babariviere/homebrew-core/.git
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/heroku/homebrew-brew/.git
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/.git
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts/.git
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/.git
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/.git
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/jesseduffield/homebrew-lazygit/.git
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae/.git
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/neovim/homebrew-neovim/.git
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/nickolasburr/homebrew-pfa/.git
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/osx-cross/homebrew-arm/.git
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/osx-cross/homebrew-avr/.git
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/paul-nameless/homebrew-repo/.git
/System/Volumes/Data/usr/local/Homebrew/Library/Taps/qmk/homebrew-qmk/.git
/System/Volumes/Data/usr/local/share/zsh/functions/_git
/System/Volumes/Data/usr/local/share/zsh/site-functions/_git
/usr/local/Cellar/git/2.33.0_1/share/zsh/site-functions/_git
/usr/local/Cellar/zsh/5.8_1/share/zsh/functions/_git
/usr/local/Homebrew/.git
/usr/local/Homebrew/Library/Taps/babariviere/homebrew-core/.git
/usr/local/Homebrew/Library/Taps/heroku/homebrew-brew/.git
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/.git
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts/.git
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/.git
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/.git
/usr/local/Homebrew/Library/Taps/jesseduffield/homebrew-lazygit/.git
/usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae/.git
/usr/local/Homebrew/Library/Taps/neovim/homebrew-neovim/.git
/usr/local/Homebrew/Library/Taps/nickolasburr/homebrew-pfa/.git
/usr/local/Homebrew/Library/Taps/osx-cross/homebrew-arm/.git
/usr/local/Homebrew/Library/Taps/osx-cross/homebrew-avr/.git
/usr/local/Homebrew/Library/Taps/paul-nameless/homebrew-repo/.git
/usr/local/Homebrew/Library/Taps/qmk/homebrew-qmk/.git
/usr/local/share/zsh/functions/_git
/usr/local/share/zsh/site-functions/_git
/usr/share/zsh/5.7.1/functions/_git
```

**Comment by molleweide** [comment]
this explains it, right, because trepo only looks in HOME and I only get dirs returned from /usr and /System

**Comment by cljoly** [comment]
Ok, so if we add the escaped dot:
```
glocate -d $HOME/locatedb -r '/\.git$'
```
we should get mostly the same list

**Comment by cljoly** [comment]
> this explains it, right, because trepo only looks in HOME and I only get dirs returned from /usr and /System

Actually, I think you should see the same output with *telescope-repo.nvim* as with the command

**Comment by molleweide** [comment]
yeah, i'll test 

> > this explains it, right, because trepo only looks in HOME and I only get dirs returned from /usr and /System
> 
> Actually, I think you should see the same output with _telescope-repo.nvim_ as with the command

hmmmm

**Comment by molleweide** [comment]
at least now by setting localpaths the correct stuff shows up in locatedb

**Comment by molleweide** [comment]
but nothing shows up in trepo cached

**Comment by molleweide** [comment]
and theterminal output is correct

**Comment by cljoly** [comment]
Hum

**Comment by molleweide** [comment]
do you know if it is possible to verify that glocate is recognized from within vim?
otherwise I'll search for it.

**Comment by molleweide** [comment]
`:! glocate -d ~/locatedb -r '/\.git$'` in vim works

**Comment by cljoly** [comment]
Also, `vim.fn.executable` should work (in Lua).

I have `plocate` but not `glocate`
image

**Comment by molleweide** [comment]
> Also, `vim.fn.executable` should work (in Lua).
> 
> I have `plocate` but not `glocate` image

sorry, im stupid, i realize that I should just have changed the string.

**Comment by cljoly** [comment]
We can try to simplify the repo pattern from `[[/\.git$]]` to `[[git$]]` or even `[[.]]`.

**Comment by cljoly** [comment]
> sorry, im stupid, i realize that I should just have changed the string.

No worries at all, that’s fine.

**Comment by molleweide** [comment]
> We can try to simplify the repo pattern from `[[/\.git$]]` to `[[git$]]` or even `[[.]]`.

nope!

**Comment by cljoly** [comment]
So still nothing in the telescope-repo.nvim output?

**Comment by molleweide** [comment]
yeah nothing

**Comment by molleweide** [comment]
i'll take a little break now.

**Comment by cljoly** [comment]
I don’t know what more to test for now sadly. Thanks for your help though!

**Comment by cljoly** [comment]
> i'll take a little break now.

Same here

**Comment by molleweide** [comment]
hopefully will figure it out later

**Comment by cljoly** [comment]
I’m still thinking about a way to solve this…

**Comment by molleweide** [comment]
Me to haha

**Comment by molleweide** [comment]
I have thinking about this pretty much 24/7 for the last couple of days but this seems to be a bit above my level of nvim so I have had to spend some time on other stuff in the mean time but I am extremely looking forward to get some more time to look into this issue again because this is probably one of the most useful plugins ever.

**Comment by cljoly** [comment]
Thanks for your enthusiasm!

I’ve added some log messages (they may need adjustments so that it is less verbose, but for now it should be fine). You can see them by typing `:messages`.

When you have some time, maybe [copy-pasting][reddit] the output in a gist for me to look into would prove insightful.

[reddit]: https://www.reddit.com/r/vim/comments/ae0t7b/how_can_i_save_messages_to_a_file_or_to_a_text/

**Comment by molleweide** [comment]
cool! I will try to do that tomorrow.
I also read a blog post that I found when searching around for how to reload plugins.

**Comment by cljoly** [comment]
If you still have the link, I would be interested, if only for comparison with what [I do](https://cj.rs/blog/tips/nvim-plugin-development/)

**Comment by molleweide** [comment]
Yo!

I pulled `locate` branch and when I run the command it shows this:
```
:!open "https://www.reddit.com/search/?q=call_picker"

Press ENTER or type command to continue
```
and it open a reddit link in my web browser

**Comment by molleweide** [comment]
> If you still have the link, I would be interested, if only for comparison with what [I do](https://cj.rs/blog/tips/nvim-plugin-development/)

I simply created a command that calls `Telescope reloader`. This seems to work when I am in the directory working on the actual plugin BUT if I am in the dir of my vimrc, then running the command I cant find any packer modules. I don't understand why yet.

**Comment by molleweide** [comment]
This shows what the preview shows me when I search for `telerepo` with reloader in my vimrc dir:

```
       8 │  nvim-treesitter.shell_command_selectors : ~/.config/dorothy                                                                                                            │
       9 │  telescope.finders : ~/.config/dorothy                                                                                                                                  │
      10 │  telescope.sorters : ~/.config/dorothy                                                                                                                                  │
      11 │  telescope.pickers : ~/.config/dorothy                                                                                                                                  │
      12 │  telescope.previewers.buffer_previewer : ~/.config/dorothy                                                                                                              │
      13 │  telescope._extensions.gh_previewers : ~/.config/dorothy                                                                                                                │
      14 │  telescope.deprecated : ~/.config/dorothy                                                                                                                               │
      15 │  telescope._extensions.mapper.previewers : ~/.config/dorothy                                                                                                            │
      16 │ telescope._extensions.repo : ~/.config/dorothy                                                                                                                          │
      17 ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
      18 ╭─────────────────────────────────────────────────────────────────────────────── Packages ────────────────────────────────────────────────────────────────────────────────╮
      19 │   telerepo                                                                                                                                                    207 / 300│
```

**Comment by molleweide** [comment]
i created a new gist.
https://gist.github.com/molleweide/1ce6a71a0b31c8fab85fccf7d87345e0

**Comment by cljoly** [comment]
Thanks, I'll look into this in the next few days!

**Comment by cljoly** [comment]
It might be that telescope can’t execute the command for some reason, I’ll try to look deeper into this…

**Comment by molleweide** [comment]
Hmm interesting!! Tell me if you want me to do something for you

**Comment by molleweide** [comment]
> It might be that telescope can’t execute the command for some reason, I’ll try to look deeper into this…

Do you think that this would be grounds for a bug submission to telescope?

**Comment by cljoly** [comment]
> Do you think that this would be grounds for a bug submission to telescope?

Maybe, I wanna read the docs some more first though.

**Comment by molleweide** [comment]
ooh i have to also read the built-in docs

**Comment by cljoly** [comment]
When I login to [this GitHub Actions Workflow (that uses Mac OS)](https://github.com/cljoly/telescope-repo.nvim-macos/blob/1a186a9a378bd48e92fc5326c5ad6889d61b574f/.github/workflows/blank.yml), I can run:
```
nvim +'lua require"telescope".extensions.repo.cached_list{bin="glocate", locate_opts={"-d", "/Users/runner/locatedb"}}'
```
and after a few seconds, I get a list of repositories, like so:
image


@molleweide You won’t be able to log in to the action as it requires one of my private SSH keys, but maybe by comparing what’s done in the `.yml`, you will find what was wrong. For instance, it appears that `$HOME` does not work, as:
```
nvim +'lua require"telescope".extensions.repo.cached_list{bin="glocate", locate_opts={"-d", "/Users/runner/locatedb"}}'
```
works as intended, while:
```
nvim +'lua require"telescope".extensions.repo.cached_list{bin="glocate", locate_opts={"-d", "$HOME/loca
tedb"}}'
```
did not return any results.
I hope this helps you getting the plugin to work with locate on your Mac.

- [ ] I still need to find if there is a way to get a more verbose error when the command fails, it’s silent at the moment.

**Comment by molleweide** [comment]
yo I've seen that you wrote. I'll try to look at this and reply as soon as I can.

**Comment by cljoly** [comment]
Thanks!

**Comment by molleweide** [comment]
No worries, i just wanted you to know I am following. I have a lot of stuff to do atm so I cant wait until I get to test this.

**Comment by cljoly** [comment]
@molleweide I’m going to merge this PR as it works for me on Linux and I want to further build on the code without creating more conflicts 😅 .

I’ve created a discussion (#13) to further investigate why the `cached_list` command did not work on Mac OS, when you have some time. We can then come back and make the [necessary changes](https://github.com/cljoly/telescope-repo.nvim/issues/14).

**Pull request merged**
