### PR TITLE
Add support for lolcate-rs as a cached_list provider.

### PR DESCRIPTION
**Pull request by dsully**
[lolcate](https://github.com/ngirard/lolcate-rs) unfortunately uses different arguments than other locate implementations.

### CODE REVIEW

**Comment by cljoly** [comment]
Thanks for the PR! Looks all good to me.

**Comment by cljoly** [comment]
I did not know about lolcate-rs, I wonder if it might be easier to install on macOS (perhaps it should be mentioned as a part of #14)

**Comment by dsully** [comment]
Definitely easier to install: `cargo install lolcate-rs`.

I can add something in the README.

Also, would you be up for a `stylua.toml` file being added and files formatted?

**Comment by cljoly** [comment]
> Definitely easier to install: `cargo install lolcate-rs`.

Yeah :) And even the database management part seems easier.

> I can add something in the README.

Sure, especially if you can test the instructions you put there on macOS (I cannot).
You might want to blend that in this particular section of the README: https://github.com/cljoly/telescope-repo.nvim#notes-for-macos

> Also, would you be up for a stylua.toml file being added and files formatted?

Yes please, by all means!
Please make the PR to be merged in the `dev` branch (per the [stability commitment](https://cj.rs/telescope-repo-nvim/#stability)), if possible. If you can’t, I’ll just edit your PR.

**Pull request merged**
